/*
 * Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *                                           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include "pch.h"
#include <iostream>

int Fibonacci(int max) {
	int n_2 = 1;
	int n_1 = 1;
	int sum = 0;

	bool end = false;

	while (!end) {
		int newTerm = n_2 + n_1;

		if (newTerm > max) {
			end = true;
			break;
		}

		if (newTerm % 2 == 0) {
			sum += newTerm;
		}

		n_2 = n_1;
		n_1 = newTerm;
	}

	return sum;
}

int main()
{
	int result = Fibonacci(4000000);
	std::cout << "Sum of the even-valued terms in the Fibonacci sequence: " << result << std::endl;
}
